name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Build Docker Images
      run: |
        docker build -t tracker-frontend -f Dockerfile .
        docker build -t tracker-backend -f Dockerfile.json-server .

    - name: Run Docker Containers
      run: |
        docker run -d -p 3000:3000 --name frontend tracker-frontend
        docker run -d -p 5000:5000 --name backend tracker-backend
